"""user model change

Revision ID: 82bfd5ed2525
Revises: 7c95aab656b0
Create Date: 2025-06-19 14:45:57.295001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bfd5ed2525'
down_revision: Union[str, None] = '7c95aab656b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_conversation_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_conversation_history')
    # ### end Alembic commands ###
