"""changes to models

Revision ID: b4dcca4df2b5
Revises: cfe70ccefeac
Create Date: 2025-06-16 02:38:08.850143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dcca4df2b5'
down_revision: Union[str, None] = 'cfe70ccefeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prize_pools', sa.Column('winner_user_id', sa.Integer(), nullable=True))
    op.add_column('prize_pools', sa.Column('paid_out', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'prize_pools', 'users', ['winner_user_id'], ['id'])
    op.add_column('users', sa.Column('payman_payee_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payman_payee_id')
    op.drop_constraint(None, 'prize_pools', type_='foreignkey')
    op.drop_column('prize_pools', 'paid_out')
    op.drop_column('prize_pools', 'winner_user_id')
    # ### end Alembic commands ###
